### ISSUE TITLE
The examples/riscv has a stuck bug

### ISSUE THREAD

**Issue by elliott10** [rcore-os/virtio-drivers#125]
Running examples/riscv will get stuck.

Like below:

![屏幕截图 2024-04-12 161449](https://github.com/rcore-os/virtio-drivers/assets/8327091/f22168e3-dfa2-4f78-bd47-562f8b00536f)

**Comment by fslongjin** [comment]
Me too. my qemu version is 
```
QEMU emulator version 6.2.0 (Debian 1:6.2+dfsg-2ubuntu6.17)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
```

**Comment by fslongjin** [comment]
This issue is a bit magical; after adding `#[inline(never)]` to the `can_pop` function in `VirtQueue` under `src/queue.rs`, the test case can running normally. Or here:

```
while !self.can_pop() {
            info!("add_notify_wait_pop: can_pop=false");
            spin_loop();
        }
```
 

By adding an output log statement, it runs normally. I suspect it might be due to a lack of volatile read?

**Comment by qwandor** [comment]
I don't think volatile access should be necessary for the used ring (e.g. in `VirtQueue::can_pop`), because it is shared memory not MMIO. My guess would be that we're missing a read barrier somewhere, which is allowing the compiler (or possibly the CPU?) to reorder memory access in a way that gives incorrect values.

**Comment by qwandor** [comment]
After talking to some other people about this, I think the issue is that we should be using atomics for some of these shared memory accesses. I'll send a PR shortly for you to test.

**Comment by qwandor** [comment]
@fslongjin Can you test if #128 fixes your issues reliably?

**Comment by fslongjin** [comment]
> @fslongjin Can you test if #128 fixes your issues reliably?

I test it but it still reports `NotReady`, this is my test case:

https://github.com/fslongjin/DragonOS-fork/tree/patch-add-virtio-blk-mmio

I initialize the virtio blk driver at: https://github.com/fslongjin/DragonOS-fork/blob/e8fbcd6ee7f9456a2e39da3963426c958289f4bf/kernel/src/driver/block/virtio_blk.rs#L62

and it reports `NotReady` at:  https://github.com/fslongjin/DragonOS-fork/blob/e8fbcd6ee7f9456a2e39da3963426c958289f4bf/kernel/src/driver/block/virtio_blk.rs#L98

The Halimpl:
https://github.com/fslongjin/DragonOS-fork/blob/e8fbcd6ee7f9456a2e39da3963426c958289f4bf/kernel/src/driver/virtio/virtio_impl.rs#L16

The mmio transport:
https://github.com/fslongjin/DragonOS-fork/blob/e8fbcd6ee7f9456a2e39da3963426c958289f4bf/kernel/src/driver/virtio/transport_mmio.rs#L22

**Comment by fslongjin** [comment]
In my test case, the `NotReady` means:

`self.can_pop()` at line 309 returns `true` but it returns `false` at line 501
![image](https://github.com/rcore-os/virtio-drivers/assets/63215266/a1fc5b8d-6cec-4319-b5c7-08950844e48b)
![image](https://github.com/rcore-os/virtio-drivers/assets/63215266/8560d451-ae75-42b8-bfb7-e0b78800f12d)

**Comment by fslongjin** [comment]
I add some debug log in qemu's source code, and found that the problem is with a judgment condition. The factor affecting this judgment condition is the value of avail_idx in avail_ring.

In my test cases, although the virtio driver sets avail_idx, it does not take effect in qemu. qemu still reads 0, therefore returning 'not ready'. In the test cases of examples/riscv, qemu is able to correctly read the avail_idx.
