### ISSUE TITLE
Some question about virtio-net

### ISSUE THREAD

**Issue by CtrlZ233** [rcore-os/virtio-drivers#76]
Hello, I am using virtio-net to implement an interrupt-controlled network driver. However, I found that interrupts cannot be triggered unless the recv method of VirtIONet is called. Do you think VirtIONet should also provide a non-blocking method like VirtIOBlk?

```rust
impl<H: Hal> VirtIOBlk<'_, H> {
  pub unsafe fn read_block_nb(
          &mut self,
          block_id: usize,
          buf: &mut [u8],
          resp: &mut BlkResp,
      ) -> Result<u16> {
        let token = self.queue.add(&[req.as_buf()], &[buf, resp.as_buf_mut()])?;
        self.header.notify(0);
    }
}
```
I guess the `header.notify` in the above code is what makes the interrupt mechanism work properly, right?

**Comment by qwandor** [comment]
Hello! `header.notify(0)` just tells the device to check virt queue 0. I believe the interrupt happens when the device uses the buffer, but it can't use a buffer if there are none available, so it's really the `self.queue.add` that is the important thing here.

I'm not very happy with `VirtIOBlk::read_block_nb` because it relies on the caller to properly manage buffers to ensure safety. We should probably rethink this design and come up with some way to provide a safe abstraction around it, but it's not immediately clear how that would look. Maybe the driver should allocate and manage the buffers itself somehow. In the meantime, yeah, I guess you could add a similar interface to `VirtIONet`.
